server:
  port: 8050
spring:
  application:
    name: feign
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaulZone: http://${eureka.instance.hostname}:8076/eureka/
feign:
  hystrix:
    enabled: true
